In [ ]:
import os
count=0
import cv2

In [ ]:
in_fight=r'.\SCVD\Videos\Fight'
out_fight=r'.\SCVD\Frames\Fight'
for filename in os.listdir(in_fight):
  #print(filename)
  vidObj = cv2.VideoCapture(in_fight+fr'\{filename}') 
  while True: 
        success, image = vidObj.read() 
        #print(success)
        # Saves the frames with frame-count 
        if success:
          cv2.resize(image,(240,240))
          cv2.imwrite(fr"{out_fight}\frame{count}.jpg", image) 
          count += 1
        else:
          break
  vidObj.release() 
  cv2.destroyAllWindows() 

In [ ]:
count=0

In [ ]:
In_non_fight=r'SCVD\Videos\Non_Fight'
Out_non_fight=r'SCVD\Frames\Non_Fight'
for filename in os.listdir(In_non_fight):
  #print(filename)
  vidObj = cv2.VideoCapture(In_non_fight+fr"\{filename}") 
  while True: 
        success, image = vidObj.read() 
        #print(success)
        # Saves the frames with frame-count 
        if success:
          cv2.resize(image,(240,240))
          cv2.imwrite(fr"{Out_non_fight}\frame{count}.jpg", image) 
          count += 1
        else:
          break
  vidObj.release() 
  cv2.destroyAllWindows() 

In [ ]:
from keras.applications.inception_v3 import InceptionV3
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras.callbacks import ModelCheckpoint, TensorBoard, EarlyStopping
#from data import DataSet
import os.path

In [ ]:
def get_model(weights='imagenet'):
    # create the base pre-trained model
    base_model = InceptionV3(weights=weights, include_top=False)

    # add a global spatial average pooling layer
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    # let's add a fully-connected layer
    x = Dense(1024, activation='relu')(x)
    # and a logistic layer
    predictions = Dense(2, activation='softmax')(x)

    # this is the model we will train
    model = Model(inputs=base_model.input, outputs=predictions)
    return model

In [ ]:
def get_generators():
    # train_datagen = ImageDataGenerator(
    #     rescale=1./255,
    #     shear_range=0.2,
    #     horizontal_flip=True,
    #     rotation_range=10.,
    #     width_shift_range=0.2,
    #     height_shift_range=0.2)

    # test_datagen = ImageDataGenerator(rescale=1./255)
    
    train_datagen = ImageDataGenerator(
        rescale=1. / 255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        validation_split=0.5,
        rotation_range=25)
    
    test_datagen = ImageDataGenerator(rescale=1. / 255,validation_split=0.5)
    
    train_generator = train_datagen.flow_from_directory(
        r'C:\Science\NAZAR Raw\Train',
        target_size=(299, 299),
        batch_size=32,
        subset='training',
        shuffle=True,
        class_mode='categorical')
    
    validation_generator = test_datagen.flow_from_directory(
        r'C:\Science\NAZAR Raw\Train',
        target_size=(299, 299),
        batch_size=32,
        subset='validation',
        shuffle=True,
        class_mode='categorical')
    return train_generator,validation_generator

In [ ]:
model = get_model()
generators = get_generators()

In [ ]:
checkpointer = ModelCheckpoint(
    filepath=os.path.join('data', 'checkpoints', 'inception.{epoch:03d}.hdf5'),
    verbose=1,
    save_best_only=True)

# Helper: Stop when we stop learning.
early_stopper = EarlyStopping(patience=10)

# Helper: TensorBoard
tensorboard = TensorBoard(log_dir=os.path.join('data', 'logs'))

In [ ]:
def train_model(model, nb_epoch, generators, callbacks=[]):
    train_generator,val_generator =generators
    model.fit_generator(
        train_generator,
        steps_per_epoch=100,
        epochs=nb_epoch,
        validation_data=val_generator,
        validation_steps=100,
        callbacks=callbacks)
    return model

In [ ]:
def freeze_all_but_top(model):
    """Used to train just the top layers of the model."""
    # first: train only the top layers (which were randomly initialized)
    # i.e. freeze all convolutional InceptionV3 layers
    for layer in model.layers[:-2]:
        layer.trainable = False

    # compile the model (should be done *after* setting layers to non-trainable)
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

def freeze_all_but_mid_and_top(model):
    """After we fine-tune the dense layers, train deeper."""
    # we chose to train the top 2 inception blocks, i.e. we will freeze
    # the first 172 layers and unfreeze the rest:
    for layer in model.layers[:172]:
        layer.trainable = False
    for layer in model.layers[172:]:
        layer.trainable = True

    # we need to recompile the model for these modifications to take effect
    # we use SGD with a low learning rate
    model.compile(
        optimizer=SGD(lr=0.0001, momentum=0.9),
        loss='categorical_crossentropy',
        metrics=['accuracy', 'top_k_categorical_accuracy'])

    return model

In [ ]:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
model = freeze_all_but_top(model)
model = train_model(model, 10, generators)

In [ ]:
for file in os.listdir(r'.\SCVD\Frames'):
  print(file)

In [ ]:
import shutil 

location=r"C:\Science\Violence-Detection-in-Videos-master\fight-detection-surv-dataset-master\Dataset"
path = os.path.join(location, '.ipynb_checkpoints') 
print(path)
# removing directory 
shutil.rmtree(path) 

In [ ]:
for file in os.listdir('/content/fight-detection-surv-  dataset/Dataset'):
  print('/content/fight-detection-surv-dataset/Dataset/'+file)

In [ ]:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
model = freeze_all_but_mid_and_top(model)
model = train_model(model, 10, generators,
                        [checkpointer, early_stopper, tensorboard])

In [ ]:
count=0
#for filename in os.listdir('/content/fight-detection-surv-dataset/noFight'):
  #print(filename)
vidObj = cv2.VideoCapture(r'C:\Science\Violence-Detection-in-Videos-master\fight-detection-surv-dataset-master\Dataset\V10.mp4') 
while True: 
        success, image = vidObj.read() 
        #print(success)
        # Saves the frames with frame-count 
        if success:
          cv2.resize(image,(299,299))
          cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\frames\frame{count}.jpg", image) 
          count += 1
        else:
          break
vidObj.release() 
cv2.destroyAllWindows() 

In [ ]:

from datetime import datetime

now = datetime.now() # current date and time

date_time = now.strftime("%m/%d/%Y, %H:%M:%S")
model.save(r'.\saved\model0301full.h5')
print('Model Saved!')

In [3]:
from tensorflow import keras

In [60]:
model= keras.models.load_model(r'.\saved\model0301half.h5')

In [2]:
import numpy as np

In [ ]:
import cv2
img=1
fight=0
non_fight=0
inp=input("Enter a room number")
cap=cv2.VideoCapture()
cap.open(f'rtsp://admin:sgis12345@172.16.16.132:554/Streaming/Channels/{str(inp)}01/')
success,frame=cap.read()
print(frame)
while success:
  status=''
  success,frame=cap.read()
  image=frame
  if image is not None:
      # # x = image.img_to_array(img)
      # x = np.expand_dims(image, axis=0)
      # images = np.vstack([x])
      # classes = model.predict(images, batch_size=10)
      # print(classes)
      # if classes[0][1]<=1/(10**30):
      #   status="FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      #   cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Fight{fight}.jpg", image)
      #   fight+=1
      # else:
      #   cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\non_fight\nonFight{non_fight}.jpg", image)
      #   status="No fight"
      #   non_fight+=1
      # cv2.putText(image,status, (0,69), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
      cv2.namedWindow("Violence Detection", cv2.WINDOW_NORMAL)
      cv2.resizeWindow("Violence Detection", 1366, 768)
      cv2.imshow("Violence Detection",image)
      cv2.waitKey(1)
      print("frame"+" "+status)
      img+=1 


In [ ]:
img=1
fight=0
non_fight=0
cap=cv2.VideoCapture(0)
success,frame=cap.read()
while success:
  status=''
  success,frame=cap.read()
  image=frame
  if image is not None:
      #x = image.img_to_array(img)
      x = np.expand_dims(image, axis=0)
      images = np.vstack([x])
      classes = model.predict(images, batch_size=10)
      print(classes)
      if classes[0][0]>0.85:
        status="|||||||||||||||||||||||||||||||||"
        cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Fight{fight}.jpg", image)
        fight+=1
      else:
        cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\non_fight\nonFight{non_fight}.jpg", image)
        status="No fight"
        non_fight+=1
      # cv2.putText(image,status, (0,69), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
      # cv2.imshow("Hey",image)
      # cv2.waitKey(0)
      print("frame"+" "+status)
      img+=1     


In [61]:
import cv2
from PIL import Image
img=1
fight=1
non_fight=1
video=''
for video in os.listdir(r".\frames"):
    image = cv2.imread(fr".\frames\{video}")
    if image is not None:
        #x = image.img_to_array(img)
        # image = image.resize((256, 256))qqqqqq
        # image.save('myimage_500.jpg')
        # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check1.jpg", image)
        # image=cv2.resize(image, (256,256))
        # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check2.jpg", check1)
        x = np.expand_dims(image, axis=0)
        images = np.vstack([x])
        classes = model.predict(images, batch_size=10)
        print(classes)
        if classes[0][0]>0.5:
            status="Fighting recorded"
            # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Fight{fight}.jpg", image)
            fight+=1
        else:
            status="No fight"
            # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\non_fight\nonFight{non_fight}.jpg", image)
            non_fight+=1
        cv2.putText(image,status, (0,69), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
        cv2.imshow("Hey",image)
        cv2.waitKey(0); cv2.destroyAllWindows()
        print(str(video)+" "+str(classes))
        img+=1   

1/1 [==============================] - 1s 1s/step
[[1. 0.]]
corwd1.jpg [[1. 0.]]
1/1 [==============================] - 2s 2s/step
[[1.000000e+00 2.474153e-32]]
crowd.jpg [[1.000000e+00 2.474153e-32]]
1/1 [==============================] - 0s 66ms/step
[[1. 0.]]
fight.jpg [[1. 0.]]
1/1 [==============================] - 0s 69ms/step
[[1. 0.]]
fight1.jpg [[1. 0.]]
1/1 [==============================] - 0s 242ms/step
[[1.0000000e+00 2.4135065e-15]]
fight3.jpg [[1.0000000e+00 2.4135065e-15]]
1/1 [==============================] - 0s 72ms/step
[[0. 1.]]
fight4.jpg [[0. 1.]]
1/1 [==============================] - 0s 226ms/step
[[0.60595226 0.39404777]]
Fightbend.jpg [[0.60595226 0.39404777]]
1/1 [==============================] - 0s 71ms/step
[[1. 0.]]
NONFIGHT.jpg [[1. 0.]]
1/1 [==============================] - 0s 221ms/step
[[2.2916573e-11 1.0000000e+00]]
NotFight.jpg [[2.2916573e-11 1.0000000e+00]]
1/1 [==============================] - 0s 213ms/step
[[1.0000000e+00 7.4813714e-24]]
simp

In [36]:
import cv2
import numpy as np
image = cv2.imread(fr"C:\Science\remains\Fight\frame9352.jpg")
if image is not None:
    # image = np.asarray(image)
    # image = image.resize((256, 256))
    # image.save('myimage_500.jpg')
    # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check1.jpg", image)
    # image=cv2.resize(image, (256,256))
    # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check2.jpg", check1)
    cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check2.jpg", image)
    x = np.expand_dims(image, axis=0)
    images = [x]
    classes = model.predict(images, batch_size=1)
    print(classes)
    if classes[0][0]>0.5:
        status="Fighting recorded"
        # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Fight{fight}.jpg", image)
        fight+=1
    else:
        status="No fight"
        # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\non_fight\nonFight{non_fight}.jpg", image)
        non_fight+=1
    cv2.putText(image,status, (0,69), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
    cv2.imshow("Hey",image)
    cv2.waitKey(0); cv2.destroyAllWindows()
    print(str(video)+" "+str(classes))
    img+=1   

1/1 [==============================] - 1s 1s/step
[[1.9209526e-10 1.0000000e+00]]
simpletalk.jpg [[1.9209526e-10 1.0000000e+00]]


In [51]:
import cv2
from PIL import Image
img=1
fight=1
non_fight=1
video=''
for video in os.listdir(r"C:\Science\remains\Fight"):
    image = cv2.imread(fr"C:\Science\remains\Fight\{video}")
    if image is not None:
        #x = image.img_to_array(img)
        # image = image.resize((256, 256))qqqqqq
        # image.save('myimage_500.jpg')
        # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check1.jpg", image)
        # image=cv2.resize(image, (256,256))
        # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Check2.jpg", check1)
        x = np.expand_dims(image, axis=0)
        images = np.vstack([x])
        classes = model.predict(images, batch_size=10)
        print(classes)
        if classes[0][0]>0.5:
            status="Fighting recorded"
            # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\fight_frames\Fight{fight}.jpg", image)
            fight+=1
        else:
            status="No fight"
            # cv2.imwrite(fr"C:\Science\Violence-Detection-in-Videos-master\non_fight\nonFight{non_fight}.jpg", image)
            non_fight+=1
        cv2.putText(image,status, (0,69), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
        cv2.imshow("Hey",image)
        cv2.waitKey(0); cv2.destroyAllWindows()
        print(str(video)+" "+str(classes))
        img+=1   

1/1 [==============================] - 3s 3s/step
[[0. 1.]]
frame10000.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame10001.jpg [[0. 1.]]
1/1 [==============================] - 2s 2s/step
[[0. 1.]]
frame10002.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame10003.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame10004.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame10005.jpg [[0. 1.]]
1/1 [==============================] - 2s 2s/step
[[0. 1.]]
frame10079.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame9351.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame9352.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]
frame9353.jpg [[0. 1.]]
1/1 [==============================] - 1s 1s/step
[[0. 1.]]


KeyboardInterrupt: 

In [ ]:
fight

Kaggle All Fight
Colab 60%
Model 10%
Model4-12 All Fight
0301Full 40%
0310Half 60%
SCVD All Non Fight